apiVersion: apps/v1 
kind: Deployment
metadata:
  name: bpatel-sumapp
  namespace : coe
  labels:
    app: bpatel-sumapp
spec:
  selector:
    matchLabels:
      app: bpatel-sumapp
  replicas: 1
  template:
    metadata:
      labels:
        app: bpatel-sumapp
    spec:
      containers:
      - name: bpatel-sumapp
        image: optumera.icp:8500/coe/bpatel-sumapp
        imagePullPolicy: Always
        ports:
        - containerPort: 9080       
---
apiVersion: v1        
kind: Service
metadata:
  name: bpatel-sumapp
  namespace : coe	  
  labels:
    app: bpatel-sumapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9080
  selector:
   app: bpatel-sumapp
